#
#
name: my_actions_basics___
env:
  APP_NAME      : 'My flask'
  DEP_PAC_NAME  : 'flask_deploy_var ${{ github.sha }}'
on: 
  push:
    branches: 
      - main
jobs:

  my_testing:

    runs-on: ubuntu-latest
    steps:
    - name: Print message Hello on testing!
      run: |
        echo " Hello World from testing!! "
    - name: Execure few commands
      run: |
        echo "hello message 1"
        echo "hello message 2"
        echo "application name :  ${{ env.APP_NAME }}"



        
  my_deploy:

    runs-on: ubuntu-latest
    steps:
    - name: Print message Hello on deploy!
      run:
        echo " Hello World from deploy!! "
    - name: printing deployment packege 
      run: |
        echo " Deploy package is :  ${{ env.DEP_PAC_NAME }}"
